-- 게시판 확장: 공지사항, 자료실, 비공개 건의함
-- 기존 setup.sql을 실행한 프로젝트에서 이 파일만 새 Query로 실행하세요.

create table public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  is_pinned boolean not null default false,
  author_name text not null default '운영진',
  published_at date not null default current_date,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.documents (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  category text not null default '공식 문서',
  file_path text not null,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.suggestions (
  id bigint generated by default as identity primary key,
  suggestion_type text not null check (suggestion_type in ('프로그램 제안','운영 개선','복지','홈페이지','기타')),
  content text not null,
  is_anonymous boolean not null default true,
  author_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default '접수' check (status in ('접수','검토 중','완료')),
  created_at timestamptz not null default now()
);

alter table public.notices enable row level security;
alter table public.documents enable row level security;
alter table public.suggestions enable row level security;

create policy "notices public read" on public.notices for select to anon, authenticated using (true);
create policy "admins insert notices" on public.notices for insert to authenticated with check (public.is_admin());
create policy "admins update notices" on public.notices for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete notices" on public.notices for delete to authenticated using (public.is_admin());

create policy "documents public read" on public.documents for select to anon, authenticated using (true);
create policy "admins insert documents" on public.documents for insert to authenticated with check (public.is_admin());
create policy "admins update documents" on public.documents for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete documents" on public.documents for delete to authenticated using (public.is_admin());

create policy "members submit suggestions" on public.suggestions for insert to authenticated
with check (author_id = auth.uid());
create policy "admins read suggestions" on public.suggestions for select to authenticated
using (public.is_admin());
create policy "admins update suggestions" on public.suggestions for update to authenticated
using (public.is_admin()) with check (public.is_admin());
create policy "admins delete suggestions" on public.suggestions for delete to authenticated
using (public.is_admin());

grant select on public.notices, public.documents to anon, authenticated;
grant insert, update, delete on public.notices, public.documents to authenticated;
grant select, update, delete on public.suggestions to authenticated;
grant insert (suggestion_type, content, is_anonymous, author_id) on public.suggestions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public)
values ('documents', 'documents', true)
on conflict (id) do nothing;

create policy "document files public read" on storage.objects for select to anon, authenticated
using (bucket_id = 'documents');
create policy "admins upload document files" on storage.objects for insert to authenticated
with check (bucket_id = 'documents' and public.is_admin());
create policy "admins update document files" on storage.objects for update to authenticated
using (bucket_id = 'documents' and public.is_admin());
create policy "admins delete document files" on storage.objects for delete to authenticated
using (bucket_id = 'documents' and public.is_admin());
