-- 활동 등록·참여자 관리
-- Supabase SQL Editor에서 이 파일만 한 번 실행하세요.

create table public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  activity_type text not null check (activity_type in ('프로젝트','스터디','세미나','행사')),
  description text not null default '',
  target text not null default '',
  schedule text not null default '',
  place text not null default '',
  capacity text not null default '',
  apply_start date,
  apply_end date,
  apply_url text not null default '',
  access text not null default 'public' check (access in ('public','member')),
  status text not null default '모집 중' check (status in ('모집 중','진행 중','완료')),
  result_note text not null default '',
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

-- 참여자: 이름은 텍스트 스냅샷으로 저장.
-- student_id는 부원 명단과의 연결 고리일 뿐이며, 명단에서 삭제(졸업/탈퇴)되면
-- 자동으로 null이 되고 member_name 텍스트는 그대로 남는다.
create table public.activity_members (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  student_id text references public.member_stats(student_id) on delete set null,
  member_name text not null,
  member_role text not null default '참여',
  created_at timestamptz not null default now(),
  unique (activity_id, member_name)
);

alter table public.activities enable row level security;
alter table public.activity_members enable row level security;

create policy "activities public read" on public.activities for select to anon
using (access = 'public');
create policy "activities member read" on public.activities for select to authenticated
using (true);
create policy "admins insert activities" on public.activities for insert to authenticated with check (public.is_admin());
create policy "admins update activities" on public.activities for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete activities" on public.activities for delete to authenticated using (public.is_admin());

create policy "activity members read" on public.activity_members for select to anon, authenticated using (true);
create policy "admins insert activity members" on public.activity_members for insert to authenticated with check (public.is_admin());
create policy "admins update activity members" on public.activity_members for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete activity members" on public.activity_members for delete to authenticated using (public.is_admin());

grant select on public.activities, public.activity_members to anon, authenticated;
grant insert, update, delete on public.activities, public.activity_members to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant all privileges on public.activities, public.activity_members to service_role;

notify pgrst, 'reload schema';
