-- 활동 사진 (아카이브 갤러리용, 활동당 여러 장)
-- Supabase SQL Editor에서 이 파일만 한 번 실행하세요.
-- 사진 파일은 기존 posters 버킷(공개 읽기·관리자 쓰기)을 함께 사용합니다.

create table public.activity_photos (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  photo_path text not null,
  created_at timestamptz not null default now()
);

alter table public.activity_photos enable row level security;

create policy "activity photos read" on public.activity_photos for select to anon, authenticated using (true);
create policy "admins insert activity photos" on public.activity_photos for insert to authenticated with check (public.is_admin());
create policy "admins delete activity photos" on public.activity_photos for delete to authenticated using (public.is_admin());

grant select on public.activity_photos to anon, authenticated;
grant insert, delete on public.activity_photos to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant all privileges on public.activity_photos to service_role;

notify pgrst, 'reload schema';
