-- 홈 히어로 배너 관리
-- Supabase SQL Editor에서 이 파일만 한 번 실행하세요.

create table public.banners (
  id bigint generated by default as identity primary key,
  eyebrow text not null default '',
  title_line1 text not null,
  title_line2 text not null default '',
  description text not null default '',
  cta_label text not null default '',
  cta_url text not null default '',
  art text not null default 'cube' check (art in ('cube','rings','network')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.banners enable row level security;

create policy "banners public read" on public.banners for select to anon, authenticated using (is_active);
create policy "admins read all banners" on public.banners for select to authenticated using (public.is_admin());
create policy "admins insert banners" on public.banners for insert to authenticated with check (public.is_admin());
create policy "admins update banners" on public.banners for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete banners" on public.banners for delete to authenticated using (public.is_admin());

grant select on public.banners to anon, authenticated;
grant insert, update, delete on public.banners to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant all privileges on public.banners to service_role;

notify pgrst, 'reload schema';
