-- SHIFT 관리자 시스템 초기 설정
-- Supabase Dashboard > SQL Editor에서 이 파일 전체를 한 번 실행하세요.

create type public.user_role as enum ('member', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text,
  department text,
  generation text,
  role public.user_role not null default 'member',
  created_at timestamptz not null default now()
);

create table public.newsletters (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  published_at date not null,
  file_path text not null,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.calendar_events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_type text not null check (event_type in ('프로젝트','스터디','세미나','행사')),
  event_date date not null,
  start_time time not null,
  place text not null default '',
  description text not null default '',
  visibility text not null default 'public' check (visibility in ('public','member')),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.newsletters enable row level security;
alter table public.calendar_events enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    case when lower(new.email) = 'shiftysdh@gmail.com' then 'admin'::public.user_role else 'member'::public.user_role end
  );
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.protect_last_admin()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if old.role = 'admin' and new.role <> 'admin'
     and (select count(*) from public.profiles where role = 'admin') <= 1 then
    raise exception '마지막 관리자의 권한은 해제할 수 없습니다.';
  end if;
  return new;
end;
$$;

create trigger protect_last_admin_before_update before update of role on public.profiles
for each row execute procedure public.protect_last_admin();

create policy "profiles read own" on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());
create policy "admins update profiles" on public.profiles for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "newsletters public read" on public.newsletters for select to anon, authenticated using (true);
create policy "admins insert newsletters" on public.newsletters for insert to authenticated with check (public.is_admin());
create policy "admins update newsletters" on public.newsletters for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete newsletters" on public.newsletters for delete to authenticated using (public.is_admin());

create policy "events public read" on public.calendar_events for select to anon, authenticated
using (visibility = 'public' or auth.uid() is not null);
create policy "admins insert events" on public.calendar_events for insert to authenticated with check (public.is_admin());
create policy "admins update events" on public.calendar_events for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete events" on public.calendar_events for delete to authenticated using (public.is_admin());

grant usage on schema public to anon, authenticated;
grant select on public.newsletters, public.calendar_events to anon;
grant select on public.profiles, public.newsletters, public.calendar_events to authenticated;
grant insert, update, delete on public.newsletters, public.calendar_events to authenticated;
grant update (role) on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public)
values ('newsletters', 'newsletters', true)
on conflict (id) do nothing;

create policy "newsletter files public read" on storage.objects for select to anon, authenticated
using (bucket_id = 'newsletters');
create policy "admins upload newsletter files" on storage.objects for insert to authenticated
with check (bucket_id = 'newsletters' and public.is_admin());
create policy "admins update newsletter files" on storage.objects for update to authenticated
using (bucket_id = 'newsletters' and public.is_admin());
create policy "admins delete newsletter files" on storage.objects for delete to authenticated
using (bucket_id = 'newsletters' and public.is_admin());
