import React, { useState } from 'react';
import { ArrowRight, Bell, ChevronRight, Download, FileText, FolderArchive, LogIn, Mail, MessageSquareText, Send } from 'lucide-react';
import { boardDescriptions } from '../data.js';
import { supabase } from '../supabase.js';
import { Button, PageHero, SectionHead } from '../components/ui.jsx';

export default function Board({newsletters,notices,documents,user}){const [cat,setCat]=useState('공지사항');const cats=[['공지사항',Bell],['뉴스레터',Mail],['건의함',MessageSquareText],['자료실',FolderArchive]];return <><PageHero eyebrow="BOARD" title={<>SHIFT의 공식 소식과<br/><em>정보를 확인하세요.</em></>} description="공지부터 운영 문서까지, 필요한 정보를 투명하게 공유합니다."/><section className="section container board-layout"><aside className="board-side"><span className="eyebrow">CATEGORY</span>{cats.map(([c,I])=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}><I/>{c}<ChevronRight/></button>)}</aside><div className="board-content"><SectionHead eyebrow="BOARD" title={cat} text={boardDescriptions[cat]}/><BoardView category={cat} newsletters={newsletters} notices={notices} documents={documents} user={user}/></div></section></>}

function BoardView({category,newsletters=[],notices=[],documents=[],user}){if(category==='공지사항')return notices.length?<div className="table-wrap"><div className="board-table notice-table table-head"><span>구분</span><span>제목</span><span>작성자</span><span>날짜</span></div>{notices.map(item=><details className="notice-detail" key={item.id}><summary className="board-table notice-table"><span>{item.is_pinned?'필독':item.id}</span><strong>{item.title}</strong><span>{item.author_name}</span><span>{item.published_at}</span></summary><div className="notice-content">{item.content}</div></details>)}</div>:<div className="board-empty"><Bell/><h3>등록된 공지사항이 없습니다</h3><p>새로운 소식이 등록되면 이곳에 표시됩니다.</p></div>;
if(category==='뉴스레터')return newsletters.length ? <div className="newsletter-grid">{newsletters.map(item=><a href={item.file_url} target="_blank" rel="noreferrer" key={item.id}><span>SHIFT LETTER · {new Date(item.published_at).toLocaleDateString('ko-KR',{year:'numeric',month:'long'})}</span><h3>{item.title}</h3><p>{item.description || 'SHIFT의 새로운 소식과 활동 이야기를 만나보세요.'}</p><ArrowRight/></a>)}</div> : <div className="board-empty"><Mail/><h3>등록된 뉴스레터가 없습니다</h3><p>관리자 페이지에서 첫 뉴스레터를 등록해주세요.</p></div>;
if(category==='건의함')return <SuggestionForm user={user}/>;
return documents.length?<div className="files">{documents.map(item=><a href={item.file_url} target="_blank" rel="noreferrer" key={item.id}><FileText/><div><b>{item.title}</b><span>{item.category} · {item.description||'공식 자료'}</span></div><Download/></a>)}</div>:<div className="board-empty"><FolderArchive/><h3>등록된 자료가 없습니다</h3><p>동아리 규칙과 공식 문서가 이곳에 게시됩니다.</p></div>}

function SuggestionForm({user}){const [form,setForm]=useState({suggestion_type:'프로그램 제안',content:'',is_anonymous:true});const [message,setMessage]=useState('');if(!user)return <div className="board-empty"><LogIn/><h3>로그인이 필요합니다</h3><p>SHIFT 회원 로그인 후 건의를 제출할 수 있습니다.</p></div>;const submit=async e=>{e.preventDefault();setMessage('');const {error}=await supabase.from('suggestions').insert({...form,author_id:user.id});if(error)setMessage(error.message);else{setForm({...form,content:''});setMessage('건의가 접수되었습니다. 내용은 운영진만 확인할 수 있습니다.')}};return <form className="suggest-form" onSubmit={submit}><label>건의 유형<select value={form.suggestion_type} onChange={e=>setForm({...form,suggestion_type:e.target.value})}>{['프로그램 제안','운영 개선','복지','홈페이지','기타'].map(x=><option key={x}>{x}</option>)}</select></label><fieldset><legend>제출 방식 (익명 선택 시에도 운영진에게는 이름이 표시됩니다)</legend><label><input type="radio" name="identity" checked={form.is_anonymous} onChange={()=>setForm({...form,is_anonymous:true})}/> 익명</label><label><input type="radio" name="identity" checked={!form.is_anonymous} onChange={()=>setForm({...form,is_anonymous:false})}/> 기명</label></fieldset><label>의견<textarea required value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder="SHIFT에 전하고 싶은 의견을 자유롭게 작성해주세요." rows="7"/></label>{message&&<div className="auth-message">{message}</div>}<Button>의견 보내기 <Send size={16}/></Button></form>}
